### ISSUE TITLE
ConcurrentModificationException in parallel build somewhere in p2 AbstractRepository

### ISSUE THREAD

**Issue by sratz** [eclipse-tycho/tycho#4709]
I just got the following in a parallel build.
- Tycho 4.0.11
- `-T 6`

I am not sure whether this this is something that needs to be synchronized in the Tycho layer (or retried, similar to #3698?), or if this is an actual bug in P2, since `AbstractRepositoryManager` already uses a `synchronized(repositoryLock) { ... }`, and it still fails.

```
[ERROR] ConcurrentModificationException
java.util.ConcurrentModificationException
    at java.util.LinkedHashMap$LinkedHashIterator.nextNode (LinkedHashMap.java:1023)
    at java.util.LinkedHashMap$LinkedEntryIterator.next (LinkedHashMap.java:1058)
    at java.util.LinkedHashMap$LinkedEntryIterator.next (LinkedHashMap.java:1055)
    at org.eclipse.equinox.internal.p2.core.helpers.OrderedProperties$UnmodifiableProperties.<init> (OrderedProperties.java:213)
    at org.eclipse.equinox.internal.p2.core.helpers.OrderedProperties.unmodifiableProperties (OrderedProperties.java:37)
    at org.eclipse.equinox.p2.repository.spi.AbstractRepository.getProperties (AbstractRepository.java:110)
    at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.addRepository (AbstractRepositoryManager.java:132)
    at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.basicGetRepository (AbstractRepositoryManager.java:197)
    at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository (AbstractRepositoryManager.java:678)
    at org.eclipse.equinox.internal.p2.artifact.repository.ArtifactRepositoryManager.loadRepository (ArtifactRepositoryManager.java:131)
    at org.eclipse.equinox.internal.p2.artifact.repository.ArtifactRepositoryManager.loadRepository (ArtifactRepositoryManager.java:125)
    at org.eclipse.tycho.p2maven.transport.P2MirrorDisablingArtifactRepositoryManager.loadRepository (P2MirrorDisablingArtifactRepositoryManager.java:94)
    at org.eclipse.tycho.p2maven.transport.RemoteArtifactRepositoryManager.lambda$loadRepository$1 (RemoteArtifactRepositoryManager.java:105)
    at org.eclipse.tycho.p2maven.transport.RemoteArtifactRepositoryManager.accessRepository (RemoteArtifactRepositoryManager.java:137)
    at org.eclipse.tycho.p2maven.transport.RemoteArtifactRepositoryManager.loadRepository (RemoteArtifactRepositoryManager.java:105)
    at org.eclipse.tycho.p2.repository.RepositoryArtifactProvider.loadRepository (RepositoryArtifactProvider.java:112)
    at org.eclipse.tycho.p2.repository.LazyArtifactRepository.getDelegate (LazyArtifactRepository.java:50)
    at org.eclipse.tycho.p2.repository.LazyArtifactRepository.contains (LazyArtifactRepository.java:87)
    at org.eclipse.tycho.p2.repository.RepositoryArtifactProvider.contains (RepositoryArtifactProvider.java:133)
    at org.eclipse.tycho.p2.repository.MirroringArtifactProvider.isFileAlreadyAvailable (MirroringArtifactProvider.java:439)
    at org.eclipse.tycho.p2.repository.CompositeArtifactProvider.lambda$isFileAlreadyAvailable$0 (CompositeArtifactProvider.java:173)
    at java.util.stream.MatchOps$1MatchSink.accept (MatchOps.java:90)
    at java.util.Spliterators$ArraySpliterator.tryAdvance (Spliterators.java:1034)
    at java.util.stream.ReferencePipeline.forEachWithCancel (ReferencePipeline.java:129)
    at java.util.stream.AbstractPipeline.copyIntoWithCancel (AbstractPipeline.java:527)
    at java.util.stream.AbstractPipeline.copyInto (AbstractPipeline.java:513)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto (AbstractPipeline.java:499)
    at java.util.stream.MatchOps$MatchOp.evaluateSequential (MatchOps.java:230)
    at java.util.stream.MatchOps$MatchOp.evaluateSequential (MatchOps.java:196)
    at java.util.stream.AbstractPipeline.evaluate (AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.anyMatch (ReferencePipeline.java:632)
    at org.eclipse.tycho.p2.repository.CompositeArtifactProvider.isFileAlreadyAvailable (CompositeArtifactProvider.java:173)
    at org.eclipse.tycho.p2resolver.TargetPlatformBaseImpl.isFileAlreadyAvailable (TargetPlatformBaseImpl.java:200)
    at org.eclipse.tycho.p2resolver.PreliminaryTargetPlatformImpl.isFileAlreadyAvailable (PreliminaryTargetPlatformImpl.java:39)
    at org.eclipse.tycho.core.resolver.DefaultP2ResolutionResult.lambda$new$1 (DefaultP2ResolutionResult.java:56)
    at java.util.stream.ReferencePipeline$3$1.accept (ReferencePipeline.java:197)
    at java.util.HashMap$KeySpliterator.forEachRemaining (HashMap.java:1715)
    at java.util.stream.AbstractPipeline.copyInto (AbstractPipeline.java:509)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto (AbstractPipeline.java:499)
    at java.util.stream.ReduceOps$ReduceOp.evaluateSequential (ReduceOps.java:921)
    at java.util.stream.AbstractPipeline.evaluate (AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.collect (ReferencePipeline.java:682)
    at org.eclipse.tycho.core.resolver.DefaultP2ResolutionResult.<init> (DefaultP2ResolutionResult.java:70)
    at org.eclipse.tycho.p2resolver.P2ResolverImpl.toResolutionResult (P2ResolverImpl.java:252)
    at org.eclipse.tycho.p2resolver.P2ResolverImpl.resolveDependencies (P2ResolverImpl.java:246)
    at org.eclipse.tycho.p2resolver.P2ResolverImpl.resolveTargetDependencies (P2ResolverImpl.java:124)
    at org.eclipse.tycho.p2resolver.P2DependencyResolver.doResolveDependencies (P2DependencyResolver.java:378)
    at org.eclipse.tycho.p2resolver.P2DependencyResolver.resolveDependencies (P2DependencyResolver.java:328)
    at org.eclipse.tycho.core.osgitools.AbstractTychoProject.lambda$getDependencyArtifacts$0 (AbstractTychoProject.java:92)
    at org.eclipse.tycho.core.osgitools.DefaultReactorProject$LazyValue.get (DefaultReactorProject.java:307)
    at org.eclipse.tycho.core.osgitools.DefaultReactorProject.computeContextValue (DefaultReactorProject.java:200)
    at org.eclipse.tycho.core.osgitools.AbstractTychoProject.getDependencyArtifacts (AbstractTychoProject.java:82)
    at org.eclipse.tycho.core.resolver.DefaultTychoResolver.resolveProject (DefaultTychoResolver.java:98)
    at org.eclipse.tycho.core.maven.TychoProjectExecutionListener.beforeProjectLifecycleExecution (TychoProjectExecutionListener.java:111)
    at org.apache.maven.lifecycle.internal.CompoundProjectExecutionListener.beforeProjectLifecycleExecution (CompoundProjectExecutionListener.java:42)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:103)
    at io.takari.maven.builder.smart.SmartBuilderImpl.buildProject (SmartBuilderImpl.java:206)
    at io.takari.maven.builder.smart.SmartBuilderImpl$ProjectBuildTask.run (SmartBuilderImpl.java:71)
    at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:572)
    at java.util.concurrent.FutureTask.run (FutureTask.java:317)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1144)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:642)
    at java.lang.Thread.run (Thread.java:1583)
[ERROR] com.sap.adt.sapgui.embedding: null: ConcurrentModificationException
java.lang.RuntimeException: com.sap.adt.sapgui.embedding: null
    at io.takari.maven.builder.smart.SmartBuilderImpl.buildProject (SmartBuilderImpl.java:209)
    at io.takari.maven.builder.smart.SmartBuilderImpl$ProjectBuildTask.run (SmartBuilderImpl.java:71)
    at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:572)
    at java.util.concurrent.FutureTask.run (FutureTask.java:317)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1144)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:642)
    at java.lang.Thread.run (Thread.java:1583)
Caused by: java.util.ConcurrentModificationException
    at java.util.LinkedHashMap$LinkedHashIterator.nextNode (LinkedHashMap.java:1023)
    at java.util.LinkedHashMap$LinkedEntryIterator.next (LinkedHashMap.java:1058)
    at java.util.LinkedHashMap$LinkedEntryIterator.next (LinkedHashMap.java:1055)
    at org.eclipse.equinox.internal.p2.core.helpers.OrderedProperties$UnmodifiableProperties.<init> (OrderedProperties.java:213)
    at org.eclipse.equinox.internal.p2.core.helpers.OrderedProperties.unmodifiableProperties (OrderedProperties.java:37)
    at org.eclipse.equinox.p2.repository.spi.AbstractRepository.getProperties (AbstractRepository.java:110)
    at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.addRepository (AbstractRepositoryManager.java:132)
    at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.basicGetRepository (AbstractRepositoryManager.java:197)
    at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository (AbstractRepositoryManager.java:678)
    at org.eclipse.equinox.internal.p2.artifact.repository.ArtifactRepositoryManager.loadRepository (ArtifactRepositoryManager.java:131)
    at org.eclipse.equinox.internal.p2.artifact.repository.ArtifactRepositoryManager.loadRepository (ArtifactRepositoryManager.java:125)
    at org.eclipse.tycho.p2maven.transport.P2MirrorDisablingArtifactRepositoryManager.loadRepository (P2MirrorDisablingArtifactRepositoryManager.java:94)
    at org.eclipse.tycho.p2maven.transport.RemoteArtifactRepositoryManager.lambda$loadRepository$1 (RemoteArtifactRepositoryManager.java:105)
    at org.eclipse.tycho.p2maven.transport.RemoteArtifactRepositoryManager.accessRepository (RemoteArtifactRepositoryManager.java:137)
    at org.eclipse.tycho.p2maven.transport.RemoteArtifactRepositoryManager.loadRepository (RemoteArtifactRepositoryManager.java:105)
    at org.eclipse.tycho.p2.repository.RepositoryArtifactProvider.loadRepository (RepositoryArtifactProvider.java:112)
    at org.eclipse.tycho.p2.repository.LazyArtifactRepository.getDelegate (LazyArtifactRepository.java:50)
    at org.eclipse.tycho.p2.repository.LazyArtifactRepository.contains (LazyArtifactRepository.java:87)
    at org.eclipse.tycho.p2.repository.RepositoryArtifactProvider.contains (RepositoryArtifactProvider.java:133)
    at org.eclipse.tycho.p2.repository.MirroringArtifactProvider.isFileAlreadyAvailable (MirroringArtifactProvider.java:439)
    at org.eclipse.tycho.p2.repository.CompositeArtifactProvider.lambda$isFileAlreadyAvailable$0 (CompositeArtifactProvider.java:173)
    at java.util.stream.MatchOps$1MatchSink.accept (MatchOps.java:90)
    at java.util.Spliterators$ArraySpliterator.tryAdvance (Spliterators.java:1034)
    at java.util.stream.ReferencePipeline.forEachWithCancel (ReferencePipeline.java:129)
    at java.util.stream.AbstractPipeline.copyIntoWithCancel (AbstractPipeline.java:527)
    at java.util.stream.AbstractPipeline.copyInto (AbstractPipeline.java:513)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto (AbstractPipeline.java:499)
    at java.util.stream.MatchOps$MatchOp.evaluateSequential (MatchOps.java:230)
    at java.util.stream.MatchOps$MatchOp.evaluateSequential (MatchOps.java:196)
    at java.util.stream.AbstractPipeline.evaluate (AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.anyMatch (ReferencePipeline.java:632)
    at org.eclipse.tycho.p2.repository.CompositeArtifactProvider.isFileAlreadyAvailable (CompositeArtifactProvider.java:173)
    at org.eclipse.tycho.p2resolver.TargetPlatformBaseImpl.isFileAlreadyAvailable (TargetPlatformBaseImpl.java:200)
    at org.eclipse.tycho.p2resolver.PreliminaryTargetPlatformImpl.isFileAlreadyAvailable (PreliminaryTargetPlatformImpl.java:39)
    at org.eclipse.tycho.core.resolver.DefaultP2ResolutionResult.lambda$new$1 (DefaultP2ResolutionResult.java:56)
    at java.util.stream.ReferencePipeline$3$1.accept (ReferencePipeline.java:197)
    at java.util.HashMap$KeySpliterator.forEachRemaining (HashMap.java:1715)
    at java.util.stream.AbstractPipeline.copyInto (AbstractPipeline.java:509)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto (AbstractPipeline.java:499)
    at java.util.stream.ReduceOps$ReduceOp.evaluateSequential (ReduceOps.java:921)
    at java.util.stream.AbstractPipeline.evaluate (AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.collect (ReferencePipeline.java:682)
    at org.eclipse.tycho.core.resolver.DefaultP2ResolutionResult.<init> (DefaultP2ResolutionResult.java:70)
    at org.eclipse.tycho.p2resolver.P2ResolverImpl.toResolutionResult (P2ResolverImpl.java:252)
    at org.eclipse.tycho.p2resolver.P2ResolverImpl.resolveDependencies (P2ResolverImpl.java:246)
    at org.eclipse.tycho.p2resolver.P2ResolverImpl.resolveTargetDependencies (P2ResolverImpl.java:124)
    at org.eclipse.tycho.p2resolver.P2DependencyResolver.doResolveDependencies (P2DependencyResolver.java:378)
    at org.eclipse.tycho.p2resolver.P2DependencyResolver.resolveDependencies (P2DependencyResolver.java:328)
    at org.eclipse.tycho.core.osgitools.AbstractTychoProject.lambda$getDependencyArtifacts$0 (AbstractTychoProject.java:92)
    at org.eclipse.tycho.core.osgitools.DefaultReactorProject$LazyValue.get (DefaultReactorProject.java:307)
    at org.eclipse.tycho.core.osgitools.DefaultReactorProject.computeContextValue (DefaultReactorProject.java:200)
    at org.eclipse.tycho.core.osgitools.AbstractTychoProject.getDependencyArtifacts (AbstractTychoProject.java:82)
    at org.eclipse.tycho.core.resolver.DefaultTychoResolver.resolveProject (DefaultTychoResolver.java:98)
    at org.eclipse.tycho.core.maven.TychoProjectExecutionListener.beforeProjectLifecycleExecution (TychoProjectExecutionListener.java:111)
    at org.apache.maven.lifecycle.internal.CompoundProjectExecutionListener.beforeProjectLifecycleExecution (CompoundProjectExecutionListener.java:42)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:103)
    at io.takari.maven.builder.smart.SmartBuilderImpl.buildProject (SmartBuilderImpl.java:206)
    at io.takari.maven.builder.smart.SmartBuilderImpl$ProjectBuildTask.run (SmartBuilderImpl.java:71)
    at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:572)
    at java.util.concurrent.FutureTask.run (FutureTask.java:317)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1144)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:642)
    at java.lang.Thread.run (Thread.java:1583)
```

**Comment by merks** [comment]
Note that the constructor copies the map:

![Image](https://github.com/user-attachments/assets/bc2f0b59-4837-4739-96a0-9b83514e56fb)

And while this this is synchronized it does not copy the map:
```
	protected synchronized void setProperties(Map<String, String> properties) {
		this.properties = properties;
	}
```
Probably it should clean the map and put all the new entries.  It should not replace the OrderedMap I think.  

Probably this should be synchronized because it's the only method that access the properties field but isn't synchronized:
``
	@Override
	public String getProperty(String key) {
		return properties.get(key);
	}
```

**Comment by merks** [comment]
This seems to be involved though not clear to me what is modifying the properties of the delegate:

![Image](https://github.com/user-attachments/assets/b429e2a1-ef62-4b9b-a2dd-b469de783da4)

**Comment by laeubi** [comment]
> This seems to be involved though not clear to me what is modifying the properties of the delegate:

I think it won't hurt to add an explicit `Map.copyOf(...)` here... even though it actually should already be a copy anyways...

**Comment by merks** [comment]
I really don't like that in p2 the OrderedMap is replaced with some arbitrary map that can be modified elsewhere and thereby bypass the synchronization guards.  I also think that getProperty not being synchronized is simply an oversight.   If those were both fixed, I'm not sure anything would need to be done in Tycho.  Or?

**Comment by laeubi** [comment]
> I really don't like that in p2 the OrderedMap is replaced with some arbitrary map that can be modified elsewhere and thereby bypass the synchronization guards.

It might be by intention... somewhere ... in any case I think its worth to try change that in P2 and see if any tests fail, if not merge it today and see if anything else fails during M3 testing.

>  I also think that getProperty not being synchronized is simply an oversight. 

I don't think it is that critical, but would not harm to do so

>  I'm not sure anything would need to be done in Tycho.

The only think is if we want to change something we should do it **now** so Tycho not needs to wait for just another release :-)

**Comment by sratz** [comment]
> [Ensure that AbstractRepository.properties cannot be replaced eclipse-equinox/p2#689](https://github.com/eclipse-equinox/p2/pull/689)

Thanks, @merks!

> > I'm not sure anything would need to be done in Tycho.
> 
> The only think is if we want to change something we should do it **now** so Tycho not needs to wait for just another release :-)

Hmm, 2025-03 isn't that far away, so unless there's an obvious way to also synchronize inside Tycho layer, I think waiting for the new p2 is good enough. It's the first time I've seen this particular error in our build which runs almost daily.

**Comment by laeubi** [comment]
Yes this will hopefully be fixed with next eclipse release and I plan to do a new release timely after maven artifacts are published and integrated!

**Comment by sratz** [comment]
Should be fixed via 4eefd1752ff603baf81e63e0c619dbb39ab91ee7 / Tycho 4.0.13.

**Comment by sratz** [comment]
I just got this exact same exception again with Tycho 4.0.13 / org.eclipse.equinox.p2.repository 2.9.300.

I don't see how this can still happen as everything is synchronized now and we never hand out the `OrderedProperties` to any caller.

**Comment by laeubi** [comment]
> I just got this exact same exception again with Tycho 4.0.13 / org.eclipse.equinox.p2.repository 2.9.300.
> 
> I don't see how this can still happen as everything is synchronized now and we never hand out the `OrderedProperties` to any caller.

`ConcurrentModificationException` does not mean it is different threads. If you iterate over a collection and then calling a method that adds/remove/... then you get a `ConcurrentModificationException` as well (depending on the collections implementation, e.g. `CopyOnWriteArrayList` is safe to be modified while iterating).

**Comment by merks** [comment]
Note that it's a wrapper around a map that can be changed under the covers.

**Comment by laeubi** [comment]
We also have some repos that delegate to others their work. Even though I can't think about why, it might of course be possible that one is modified while the other is init some things or is accessed by another.

Given that the map is tried to be copied here, one might catch the error, then sleep for a few milliseconds and try the copy again...

**Comment by sratz** [comment]
I still don't understand how this can happen:

```
java.util.ConcurrentModificationException
    at java.util.LinkedHashMap$LinkedHashIterator.nextNode (LinkedHashMap.java:1023)
    at java.util.LinkedHashMap$LinkedEntryIterator.next (LinkedHashMap.java:1058)
    at java.util.LinkedHashMap$LinkedEntryIterator.next (LinkedHashMap.java:1055)
    at org.eclipse.equinox.internal.p2.core.helpers.OrderedProperties$UnmodifiableProperties.<init> (OrderedProperties.java:213)
    at org.eclipse.equinox.internal.p2.core.helpers.OrderedProperties.unmodifiableProperties (OrderedProperties.java:37)
    at org.eclipse.equinox.p2.repository.spi.AbstractRepository.getProperties (AbstractRepository.java:110)
```
- The map is private to `AbstractRepository`:
    `private final Map<String, String> properties = new OrderedProperties();`
- The Map itself is never handed out as-is from `AbstractRepository` to anyone else
- All methods working with `properties` are synchronized
- `synchronized getProperties()` calls `OrderedProperties.unmodifiableProperties(properties)`, which does a simple loop over the entires.

Since everything is already synchronized I don't see how looping over the map entires can lead to a `ConcurrentModificationException`.

Am I missing something here?

**Comment by merks** [comment]
Yes, I see your point now.   OrderedProperties.UnmodifiableProperties.UnmodifiableProperties(Map<String, String>) is making a copy and AbstractRepository.getProperties  is holding a lock while all other methods that access the properties field are synchronized too.  😕

**Comment by laeubi** [comment]
Maybe somewhere we do something nasty with reflection... from code point of view it looks safe (given the fix was integrated in Tycho 4.0.13)

**Comment by merks** [comment]
Like this:

<img width="872" height="232" alt="Image" src="https://github.com/user-attachments/assets/267d0caa-9986-4679-a91c-651f1c82397c" />

Probably org.eclipse.equinox.p2.repository.spi.AbstractRepository.setProperty(String, String, IProgressMonitor) doesn't work because it calls org.eclipse.equinox.p2.repository.spi.AbstractRepository.assertModifiable().

Maybe the use of it should be like this:

<img width="821" height="233" alt="Image" src="https://github.com/user-attachments/assets/357c185e-3edc-4496-ae15-cfddd25c8776" />

**Comment by sratz** [comment]
Oh, good catch!

I haven't thought about such reflection hacks and was only looking inside p2 for references.

Yes, synchronizing on that is necessary then (I think it suffices to do this just around the remove() call (as the properties field is now final).

I'll open a PR.

**Comment by laeubi** [comment]
> I haven't thought about such reflection hacks and was only looking inside p2 for references.

 The problem is that often we have the problem that P2 is kind of "legacy" and we hardly can change it. Then changes in P2 require a full release to bubble up to Tycho. So sometimes we have some hacks to workaround these issues.

In general it would of course better to check if we can get this working without the need of these and enhance P2 then get rid of it in the next release cycle.
